---
abstract: 'Perl client for the Merchant e-Solutions Payment Gateway'
author:
  - 'Fred Moyer <fred@redhotpenguin.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MES
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  Moo: 0
  URI: 0
version: 0.01
